project:
  type: book
  output-dir: docs
  resources:
    - resources
    - 2627/misc/practice/practice.html
execute:
  freeze: auto
  warnings: false
  echo: false
book:
  title: Statistics 1 and 2
  navbar:
    left:
      - text: "Practice"
        href: 2627/misc/practice/practice.html
  subtitle: ''
  author: Don van den Bergh & Caspar J. Van Lissa
  doi: ''
  license: CC-BY
  downloads: [pdf]
  site-url: https://vandenman.github.io/stats12/
  repo-url: https://github.com/vandenman/stats12
  description: Book Description
  cover-image: images/logos/logo.jpg
  image: images/logos/logo.jpg
  favicon: images/logos/favicon.png
  cookie-consent: false
  google-analytics: ''
  page-navigation: true
  search: true
  sharing:
  - twitter
  - facebook
  - linkedin
  sidebar:
    title: ''
    logo: ''
    search: true
    contents: ''
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ''
    footer: ''
  margin-header: ''
  page-footer: CC-BY (2023) Caspar J. Van Lissa
  chapters:
  - index.qmd
  - statistics1.qmd
  - introduction.qmd
  - chapter2_descriptive_statistics.qmd
  - Chapter3_Correlation.qmd
  - probability.qmd
  - samplingdistribution.qmd
  - Week_4.qmd
  - testing.qmd
  - glm1_regression.qmd
  - glm2_sum_squares.qmd
  - glm_assumptions.qmd
  - glm3binary.qmd
  - glm4anova.qmd
  - glm5multiple.qmd
  - glm6nested.qmd
  - glm7interaction.qmd
  - logistic.qmd
  - glm_contrasts.qmd
  - factorial.qmd
  - ancova.qmd
  - rmanova.qmd
  - reliability_validity.qmd
  - data_reduction.qmd
  - confint.qmd
  - Week_13.qmd
  appendices:
  - data.qmd
  - probability_tables.qmd
  - formula_sheet2.qmd
  - references.qmd
prefer-html: true
bibliography: include/references.bib
csl: include/apa.csl
format:
  html:
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    - include/webex.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    mainfont: ''
    monofont: ''
    include-after-body:
    - include/webex.js
    - include/script.js
    - include/webex.js
  pdf:
    include-in-header: preamble.tex
    extra_dependencies: tcolorbox
    output-file: "Statistics-1-and-2"
    output-ext:  "pdf"
